data: /mnt/code/lsa_dat/model/spoc/config/spoc_v/out/spoc_v
save_model: /mnt/code/lsa_dat/model/spoc/config/spoc_v/out/transformer
log_file: /mnt/code/lsa_dat/model/spoc/config/spoc_v/log_t.txt

world_size: 1
gpu_ranks: 1

save_checkpoint_steps: 1000
valid_steps: 1000
train_steps: 20000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
 
batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1


param_init_glorot: 'true'
position_encoding: 'true'

enc_layers: 3
dec_layers: 3
