src: data/input-tok-testw-src.tsv
tgt: data/input-tok-testw-tgt.tsv
output: /dev/null

replace_unk: true
verbose: true
beam_size: 100
n_best: 100
gpu: 0
batch_size: 256     # Use 1 for large beam_size (~1000), reduces memory load
