data: out/preprocessed
save_model: out/model_trans
log_file: out/log_trans.txt

world_size: 1
gpu_ranks: 0

save_checkpoint_steps: 1000
valid_steps: 1000
train_steps: 20000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8
 
accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
 
batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1
 
max_generator_batches: 2
 
param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

enc_layers: 3
dec_layers: 3
